update scripts.

diff --git a/main/skylar_backup b/main/skylar_backup
--- a/main/skylar_backup
+++ b/main/skylar_backup
@@ -9,6 +9,7 @@ BACKUP_BASE_DIR="/backup/container_main"
 BACKUPDIR=""
 DIRRECTORY=""                       # the relative directory path of backup files. 
 RESERVE_SIZE=5                      # reserve space size GB
+BACKUP_FILE=""
 
 SKYLARMINIDE_DIR="/opt/tools/skylarminide"
 
@@ -16,11 +17,11 @@ usage() {
     echo "
 usage:
 
-docker exec -it main bash backup [options]
+docker exec main backup [options]
 
 the most commonly options are:
--d  directory       the relative directory path of backup files. 
-                    default is the timestamp. e.g: -d 20161201000000
+-f  file            backup data to the specify file. default is: /backup/container_main/<timestamp>.tar. 
+                    e.g: -f /backup/container_main/20161201000000.tar
 
 -r  reservespace    the reserve space size (unit GBytes). Backup will return error
                     if there is not enough reserve space. default is 5GB. e.g: -r 10
@@ -29,35 +30,59 @@ the most commonly options are:
 -h                  show this usage.
 
 example:
-docker exec -it main bash backup
+docker exec main backup
 "
     exit 0
+}
+
+## skylar_log <level> <content>
+skylar_log() {
+    echo "$2"
+    echo  "`date` $1 $2" >> /var/log/skylar_backup_restore.log
 }
 
 ## we will create a directory specified by argument '-d'.
 ## if '-d' is empty, we will create a default directory named by timestamp. 
 create_backup_dir() {
-    echo "==> create backup directory ..."
+    skylar_log "INFO" "==> create backup directory ..."
+    [ ! -d $BACKUP_BASE_DIR ] && mkdir -p $BACKUP_BASE_DIR
+}
 
-    if [ "$DIRRECTORY" == "" ]; then
-        DIRRECTORY=`date "+%Y%m%d%H%M%S"`
+check_args_valid() {
+    if [ "$BACKUP_FILE" == "" ]; then
+        datetime=`date "+%Y%m%d%H%M%S"`
+        BACKUP_FILE="$BACKUP_BASE_DIR/$datetime"".tar"
     fi
 
-    BACKUPDIR="$BACKUP_BASE_DIR/$DIRRECTORY"
-
-    if [ -d $BACKUPDIR ]; then
-        echo "ERROR. $BACKUPDIR is already exsit."
+    FILE=`basename $BACKUP_FILE`
+    echo "$FILE" | grep -q '^[a-zA-Z0-9\.]\+$' >>/dev/null
+    if [ $? -ne 0 ]; then
+        skylar_log "ERROR" "Invalid name of backupfile: $BACKUP_FILE"
         exit 1
     fi
 
-    mkdir -p $BACKUPDIR
-}
+    echo "$BACKUP_FILE" | grep '.tar' >>/dev/null
+    if [ $? -ne 0 ]; then
+        skylar_log "ERROR" "Invalid name of backupfile: $BACKUP_FILE"
+        exit 1
+    fi
 
+    echo "$BACKUP_FILE" | grep '/backup/container_main' >>/dev/null
+    if [ $? -ne 0 ]; then
+        skylar_log "ERROR" "Invalid name of backupfile: $BACKUP_FILE"
+        exit 1
+    fi
+
+    if [ -f $BACKUP_FILE ]; then
+        skylar_log "ERROR" "$BACKUP_FILE is exist."
+        exit 1
+    fi
+}
 
 ## check_space $need_size. unit Bytes. 
 ## return 0 if free space is enough, else return 1.
 check_space() {
-    echo "==> check space ..."
+    skylar_log "INFO" "==> check space ..."
 
     need_size=0
     if [ "$1" != "" ] && [ "$1" -gt 0 ]; then
@@ -66,6 +91,11 @@ check_space() {
 
     cd /
     total_free_size=`df | grep '/dev/mapper/docker' | awk '{print $4}'`
+    df | grep '/etc/hosts' >>/dev/null
+    if [ $? -eq 0 ]; then
+        total_free_size=`df | grep '/dev/mapper/docker' | awk '{print $4}'`
+    fi
+
     let total_free_size=$total_free_size*1024
     let free_size=$total_free_size-$need_size
     let reserve_bytes=$RESERVE_SIZE*1024*1024
@@ -75,11 +105,11 @@ check_space() {
     let free_size_MB=$free_size/1024/1024
     let reserve_size_MB=$reserve_bytes/1024/1024
 
-    echo "==> compute space size ..."
-    echo "total_free_size=$total_free_size_MB MBytes."
-    echo "need_size=$need_size_MB MBytes."
-    echo "free_size=$free_size_MB MBytes."
-    echo "reserve_size=$reserve_size_MB MBytes."
+    skylar_log "INFO" "==> compute space size ..."
+    skylar_log "INFO" "total_free_size=$total_free_size_MB MBytes."
+    skylar_log "INFO" "need_size=$need_size_MB MBytes."
+    skylar_log "INFO" "free_size=$free_size_MB MBytes."
+    skylar_log "INFO" "reserve_size=$reserve_size_MB MBytes."
 
     if [ $free_size -lt $reserve_bytes ]; then
         return 1
@@ -89,67 +119,47 @@ check_space() {
 }
 
 backup_skylarminide() {
-    echo "==> start to backup skylarminide ..."
+    skylar_log "INFO" "==> start to backup skylarminide ..."
 
     if [ ! -d $SKYLARMINIDE_DIR ] || [ ! -d "$SKYLARMINIDE_DIR/data" ]; then
         echo "ERROR. cannot find directory: $SKYLARMINIDE_DIR/data."
         return 1
     fi
 
-    echo "==> supervisorctl stop skylarminide ..."
+    skylar_log "INFO" "==> supervisorctl stop skylarminide ..."
     supervisorctl stop skylarminide
 
-    # check space before tar. 100MB
-    check_space 100000000  
-
-    cd $SKYLARMINIDE_DIR
-    echo "==> tar $SKYLARMINIDE_DIR/data ..."
-    [ -f data.tar ] && rm -f data.tar
-    tar cvf data.tar data >>/dev/null
-
-    echo "==> supervisorctl start skylarminide ..."
-    supervisorctl start skylarminide
-
-    if [ ! -e data.tar ]; then
-        echo "ERROR. tar failed: data.tar"
-        return 1
-    fi
-
-    [ -f data.tar.gz ] && rm -f data.tar.gz
-    gzip data.tar
-    if [ $? -ne 0 ]; then
-        echo "ERROR. gzip $SKYLARMINIDE_DIR/data failed."
-        return 1
-    fi
-
-    need_size=`ls -l $SKYLARMINIDE_DIR/data.tar.gz | awk '{print $5}'`
-    check_space $need_size
-    if [ $? -ne 0 ]; then
-        echo "ERROR. There is not enough reserve space to backup $SKYLARMINIDE_DIR/data.tar.gz. Reserve size is $RESERVE_SIZE GB."
-        return 1
-    fi
+    # check space before tar. 1GB
+    check_space 1000000000  
 
     create_backup_dir
+    cd $SKYLARMINIDE_DIR
+    skylar_log "INFO" "==> backup data to $BACKUP_FILE ..."
+    tar cvf $BACKUP_FILE data
 
-    echo "==> backup to $BACKUPDIR ..."
-    mv $SKYLARMINIDE_DIR/data.tar.gz $BACKUPDIR
+    skylar_log "INFO" "==> supervisorctl start skylarminide ..."
+    supervisorctl start skylarminide
 
     return 0
 }
 
 main() {
+    if ! check_args_valid; then
+        exit 1
+    fi
+
     backup_skylarminide
 
     if [ $? -eq 0 ]; then
-        echo "Done."
+        skylar_log "INFO" "Done."
         exit 0
     else
-        echo "Failed."
+        skylar_log "ERROR" "Failed."
         exit 1
     fi
 }
 
-args=`getopt "d:r:hV" $*`
+args=`getopt "f:r:hV" $*`
 if [ $? -ne 0 ]
 then
     usage
@@ -159,7 +169,7 @@ set -- $args
 for i in $*
 do
     case "$i" in
-    -d) DIRRECTORY=$2; shift 2;;
+    -f) BACKUP_FILE=$2; shift 2;;
     -r) RESERVE_SIZE=$2; shift 2;;
     -h) usage;;
     -V) echo "version $VERSION"; exit 0;;
diff --git a/pg/skylar_backup b/pg/skylar_backup
--- a/pg/skylar_backup
+++ b/pg/skylar_backup
@@ -6,11 +6,15 @@
 
 VERSION="1.0.0"
 BACKUP_BASE_DIR="/backup/container_pg"
-BACKUPDIR=""
+BACKUP_FILE=""
 DIRRECTORY=""                       # the relative directory path of backup files. 
 RESERVE_SIZE=5                      # reserve space size GB
 
 PG_DUMP_FILE="/var/lib/postgresql/dump.sql"
+PG_CONF=`find -P /var/lib/postgresql -name "postgresql.conf"`
+PG_AUTO_CONF=`find -P /var/lib/postgresql -name "postgresql.auto.conf"`
+PG_IDENT_CONF=`find -P /var/lib/postgresql -name "pg_ident.conf"`
+PG_HBA_CONF=`find -P /var/lib/postgresql -name "pg_hba.conf"`
 
 
 usage() {
@@ -19,11 +23,11 @@ Backup pg data without stopping service.
 
 usage:
 
-docker exec -it pg bash backup [options]
+docker exec pg backup [options]
 
 the most commonly options are:
--d  directory       the relative directory path of backup files. 
-                    default is the timestamp. e.g: -d 20161201000000
+-f  file            backup data to the specify file. default is: /backup/container_main/<timestamp>.tar. 
+                    e.g: -f /backup/container_main/20161201000000.tar
 
 -r  reservespace    the reserve space size (unit GBytes). Backup will return error
                     if there is not enough reserve space. default is 5GB. e.g: -r 10
@@ -32,32 +36,60 @@ the most commonly options are:
 -h                  show this usage.
 
 example:
-docker exec -it pg bash backup
+docker exec pg backup
 "
     exit 0
 }
 
+## skylar_log <level> <content>
+skylar_log() {
+    echo "$2"
+    echo  "`date` $1 $2" >> /var/log/skylar_backup_restore.log
+}
 
-create_backup_dir() {
-    if [ "$DIRRECTORY" == "" ]; then
-        DIRRECTORY=`date "+%Y%m%d%H%M%S"`
+check_args_valid() {
+    if [ "$BACKUP_FILE" == "" ]; then
+        datetime=`date "+%Y%m%d%H%M%S"`
+        BACKUP_FILE="$BACKUP_BASE_DIR/$datetime"".tar"
     fi
 
-    BACKUPDIR="$BACKUP_BASE_DIR/$DIRRECTORY"
-
-    if [ -d $BACKUPDIR ]; then
-        echo "ERROR. $BACKUPDIR is already exsit."
+    FILE=`basename $BACKUP_FILE`
+    echo "$FILE" | grep -q '^[a-zA-Z0-9\.]\+$' >>/dev/null
+    if [ $? -ne 0 ]; then
+        skylar_log "ERROR" "Invalid name of backupfile: $BACKUP_FILE"
         exit 1
     fi
 
-    mkdir -p $BACKUPDIR
-    chmod -R 777 $BACKUPDIR
+    echo "$BACKUP_FILE" | grep '.tar' >>/dev/null
+    if [ $? -ne 0 ]; then
+        skylar_log "ERROR" "Invalid name of backupfile: $BACKUP_FILE"
+        exit 1
+    fi
+
+    echo "$BACKUP_FILE" | grep '/backup/container_pg' >>/dev/null
+    if [ $? -ne 0 ]; then
+        skylar_log "ERROR" "Invalid name of backupfile: $BACKUP_FILE"
+        exit 1
+    fi
+
+    if [ -f $BACKUP_FILE ]; then
+        skylar_log "ERROR" "$BACKUP_FILE is exist."
+        exit 1
+    fi
+}
+
+create_backup_dir() {
+    [ ! -d "$BACKUP_BASE_DIR" ] && mkdir -p $BACKUP_BASE_DIR
+
+    if [ "$DIRRECTORY" == "" ]; then
+        DIRRECTORY=`date "+%Y%m%d%H%M%S"`
+    fi
 }
 
 
 ## check_space $need_size. unit Bytes. return 0 or 1
 check_space() {
-    echo "==> check space ..."
+    skylar_log "INFO" "==> check space ..."
 
     need_size=0
     if [ "$1" != "" ]; then
@@ -66,6 +98,11 @@ check_space() {
 
     cd /
     total_free_size=`df | grep '/dev/mapper/docker' | awk '{print $4}'`
+    df | grep '/etc/hosts' >>/dev/null
+    if [ $? -eq 0 ]; then
+        total_free_size=`df | grep '/dev/mapper/docker' | awk '{print $4}'`
+    fi
+
     let total_free_size=$total_free_size*1024
     let free_size=$total_free_size-$need_size
     let reserve_bytes=$RESERVE_SIZE*1024*1024
@@ -75,11 +112,11 @@ check_space() {
     let free_size_MB=$free_size/1024/1024
     let reserve_size_MB=$reserve_bytes/1024/1024
 
-    echo "==> compute space size ..."
-    echo "total_free_size=$total_free_size_MB MBytes."
-    echo "need_size=$need_size_MB MBytes."
-    echo "free_size=$free_size_MB MBytes."
-    echo "reserve_size=$reserve_size_MB MBytes."
+    skylar_log "INFO" "==> compute space size ..."
+    skylar_log "INFO" "total_free_size=$total_free_size_MB MBytes."
+    skylar_log "INFO" "need_size=$need_size_MB MBytes."
+    skylar_log "INFO" "free_size=$free_size_MB MBytes."
+    skylar_log "INFO" "reserve_size=$reserve_size_MB MBytes."
     if [ $free_size -lt $reserve_bytes ]; then
         return 1
     fi
@@ -87,49 +124,64 @@ check_space() {
     return 0
 }
 
-backup_dump_file() {
-    echo "==> start to backup dump file ..."
+backup_pg() {
+    skylar_log "INFO" "==> start to backup dump file ..."
 
     supervisorctl status postgres | grep 'RUNNING' >>/dev/null
     if [ $? -ne 0 ]; then
-        echo "ERROR. postgres is not RUNNING."
-        return 1
+        skylar_log "WARN" "WARN. postgres is not RUNNING. starting pg."
+
+        kill -9 $(ps -ef | grep postgres | awk {'print $2'})
+        supervisorctl start postgres
     fi
 
     # assume that dump.sql is 2GB
     dump_file_size=2000000000
     check_space $dump_file_size
     if [ $? -ne 0 ]; then
-        echo "ERROR. There is not enough space to dump."
+        skylar_log "ERROR" "ERROR. There is not enough space to dump."
         return 1
     fi
 
     create_backup_dir
 
-    echo "==> pg_dumpall > $BACKUPDIR/dump.sql ..."
-    su postgres -c "pg_dumpall > $BACKUPDIR/dump.sql"
-
+    skylar_log "INFO" "==> pg_dumpall > $PG_DUMP_FILE ..."
+    su postgres -c "pg_dumpall > $PG_DUMP_FILE"
     if [ $? -ne 0 ]; then
-        echo "ERROR. pg_dumpall failed."
+        skylar_log "ERROR" "ERROR. failed while execute command: pg_dumpall."
         return 1
     fi
+
+    cd $BACKUP_BASE_DIR
+    rm -f dump.sql postgresql.conf pg_hba.conf postgresql.auto.conf pg_ident.conf
+    mv -f $PG_DUMP_FILE $BACKUP_BASE_DIR
+    cp -f $PG_CONF $BACKUP_BASE_DIR
+    cp -f $PG_HBA_CONF $BACKUP_BASE_DIR
+    cp -f $PG_AUTO_CONF $BACKUP_BASE_DIR
+    cp -f $PG_IDENT_CONF $BACKUP_BASE_DIR
+    tar cvf $BACKUP_FILE dump.sql postgresql.conf pg_hba.conf postgresql.auto.conf pg_ident.conf
+    rm -f dump.sql postgresql.conf pg_hba.conf postgresql.auto.conf pg_ident.conf
 
     return 0
 }
 
 main() {
-    backup_dump_file
+    if ! check_args_valid; then
+        exit 1
+    fi
+
+    backup_pg
 
     if [ $? -eq 0 ]; then
-        echo "Done."
+        skylar_log "INFO" "Done."
         exit 0
     else
-        echo "Failed."
+        skylar_log "ERROR" "Failed."
         exit 1
     fi
 }
 
-args=`getopt "d:r:hV" $*`
+args=`getopt "f:r:hV" $*`
 if [ $? -ne 0 ]
 then
     usage
@@ -139,7 +191,7 @@ set -- $args
 for i in $*
 do
     case "$i" in
-    -d) DIRRECTORY=$2; shift 2;;
+    -f) BACKUP_FILE=$2; shift 2;;
     -r) RESERVE_SIZE=$2; shift 2;;
     -h) usage;;
     -V) echo "version $VERSION"; exit 0;;
diff --git a/pg/skylar_restore b/pg/skylar_restore
--- a/pg/skylar_restore
+++ b/pg/skylar_restore
@@ -9,36 +9,64 @@ BACKUP_BASE_DIR="/backup/container_pg"
 DIRRECTORY=""                       # the relative directory path of backup files. 
 RESERVE_SIZE=5                      # reserve space size GB
 INDEX=""
-INITDB_BIN=`find -P /usr/lib/postgresql -name "initdb"`
-PGCTL_BIN=`find -P /usr/lib/postgresql -name "pg_ctl"`
+INITDB_BIN=`find -P /usr/lib/postgresql/ -name "initdb"`
+PGCTL_BIN=`find -P /usr/lib/postgresql/ -name "pg_ctl"`
 BACKUP_FILE=""
 PG_DATA_DIR="/var/lib/postgresql/9.5/main"
+PG_DATA_OLD="/var/lib/postgresql/9.5/main_old"
+
+PG_DUMP_FILE=""
+PG_CONF_FILE=""
+PG_HBA_CONF=""
+PG_AUTO_CONF=""
+PG_IDENT_CONF=""
+
 
 usage() {
     echo "
 usage:
 
-docker exec -it pg bash restore [options]
+docker exec pg restore [options]
 
 the most commonly options are:
--i      restore with a directory by index. 
-        default is by index, and index=1. e.g: -i 2
+-i  index    restore with a directory by index. 
+             default is by index, and index=1. e.g: -i 2
 
--d      restore by a specify directory. Notice that It will use 
-        index if -i is not empty. e.g: -d a1b2c3d4e5
+-f  file     restore by a specify file. Notice that It will use 
+             index if -i is not empty. e.g: -f /backup/container_pg/20161212000000.tar
 
 -h      show this usage.     
 
 example:
-docker exec -it pg bash restore
+docker exec pg restore
 "
     exit 0
 }
 
+## skylar_log <level> <content>
+skylar_log() {
+    echo "$2"
+    echo  "`date` $1 $2" >> /var/log/skylar_backup_restore.log
+}
 
+
+check_args_valid() {
+    if [ "$INDEX" != "" ] && [ "$INDEX" -lt 1 ]; then
+        skylar_log "ERROR" "ERROR. invalid index"
+        return 1
+    fi
+    if [ "$BACKUP_FILE" != "" ]; then
+        if [ ! -f "$BACKUP_FILE" ]; then
+            skylar_log "ERROR" "ERROR. cannot find file: $BACKUP_FILE"
+            return 1
+        fi
+    fi
+
+    return 0
+}
 ## check_space $need_size. return 0 or 1
 check_space() {
-    echo "==> check space ..."
+    skylar_log "INFO" "==> check space ..."
 
     need_size=0
     if [ "$1" != "" ]; then
@@ -56,11 +84,11 @@ check_space() {
     let free_size_MB=$free_size/1024/1024
     let reserve_size_MB=$reserve_bytes/1024/1024
 
-    echo "==> compute space size ..."
-    echo "total_free_size=$total_free_size_MB MBytes."
-    echo "need_size=$need_size_MB MBytes."
-    echo "free_size=$free_size_MB MBytes."
-    echo "reserve_size=$reserve_size_MB MBytes."
+    skylar_log "INFO" "==> compute space size ..."
+    skylar_log "INFO" "total_free_size=$total_free_size_MB MBytes."
+    skylar_log "INFO" "need_size=$need_size_MB MBytes."
+    skylar_log "INFO" "free_size=$free_size_MB MBytes."
+    skylar_log "INFO" "reserve_size=$reserve_size_MB MBytes."
 
     if [ $free_size -lt $reserve_bytes ]; then
         return 1
@@ -69,123 +97,138 @@ check_space() {
     return 0
 }
 
-
-restore_pg() {
-    echo "==> start to restore pg ..."
-
-    ## first time. check whether postgres is running.
-    supervisorctl restart postgres >>/dev/null
-
-    ## second time. if postgres start failed, maybe pg's data is broken. cleanup it. 
-    supervisorctl status postgres | grep 'RUNNING' >> /dev/null
-    if [ $? -ne 0 ]; then
-        echo "WARN. try to start pg failed. pg's data may be broken. we will rebuilt it."
-
-        echo "==> rebuilt a new database ..."
-        rm -rf /var/lib/postgresql/9.*/main/
-        if [ ! -d "$PG_DATA_DIR" ]; then
-            mkdir -p "$PG_DATA_DIR"
-            chown -R postgres:postgres $PG_DATA_DIR
-            chmod -R 700 $PG_DATA_DIR
-        fi
-
-        su postgres -c "$INITDB_BIN -D $PG_DATA_DIR"
-        sleep 5
-        su postgres -c "$PGCTL_BIN -D $PG_DATA_DIR -l logfile stop"
-        echo "==> rebuilt ok."
-        supervisorctl start postgres
-    fi
-
+check_backup_file() {
     ## try to use index at first.
     if [ "$INDEX" != "" ] && [ "$INDEX" -gt 0 ]; then
-        DIRRECTORY=`ls -lt | sed '1d' | sed -n "$INDEXp" | awk '{print $9}'`
-        if [ "$DIRRECTORY" == "" ]; then
-            echo "ERROR. get an invalid index:$INDEX."
+        cd $BACKUP_BASE_DIR
+        FILE=`ls -lt | sed '1d' | sed -n "$INDEX p" | awk '{print $9}'`
+        if [ ! -f "$FILE" ]; then
+            skylar_log "ERROR" "ERROR. get an invalid index:$INDEX."
             return 1
         fi
+        BACKUP_FILE=$BACKUP_BASE_DIR/$FILE
     fi
 
-    if [ "$DIRRECTORY" == "" ] && [ "$INDEX" == "" ]; then
+    if [ "$BACKUP_FILE" == "" ] && [ "$INDEX" == "" ]; then
         if [ ! -d $BACKUP_BASE_DIR ]; then
-            echo "ERROR. cannot find directory $BACKUP_BASE_DIR."
+            skylar_log "ERROR" "ERROR. cannot find directory $BACKUP_BASE_DIR."
             return 1
         fi
         cd $BACKUP_BASE_DIR
-        DIRRECTORY=`ls -lt | sed '1d' | head -1 | awk '{print $9}'`
-        if [ "$DIRRECTORY" == "" ]; then
-            echo "ERROR. Backup directory is empty."
-            return 1
-        fi
+
+        FILE=`ls -lt | sed '1d' | head -1 | awk '{print $9}'`
+        BACKUP_FILE=$BACKUP_BASE_DIR/$FILE
     fi
 
-    BACKUP_FILE="$BACKUP_BASE_DIR/$DIRRECTORY/dump.sql"
-
-    if [ ! -e $BACKUP_FILE ]; then
-        echo "ERROR. cannot find backup file: $BACKUP_FILE"
+    if [ ! -f "$BACKUP_FILE" ]; then
+        skylar_log "ERROR" "ERROR. Backup directory is empty."
         return 1
     fi
 
     size=`ls -l $BACKUP_FILE | awk '{print $5}'`
     check_space $size
     if [ $? -ne 0 ]; then
-        echo "ERROR. There is not enough reserve space to restore. reserve size is $RESERVE_SIZE GB."
+        skylar_log "ERROR" "ERROR. There is not enough reserve space to restore. reserve size is $RESERVE_SIZE GB."
         return 1
     fi
 
-    DBNAMES=$(su postgres -c "psql -P format=Unaligned -tqc 'SELECT datname FROM pg_database;' | sed 's/ /%/g'")
-    DBEXCLUDE=("postgres template0 template1")
+    [ -d $BACKUP_BASE_DIR/tmp ] && rm -rf $BACKUP_BASE_DIR/tmp
+    mkdir -p $BACKUP_BASE_DIR/tmp
+    cd $BACKUP_BASE_DIR
+    tar xvf $BACKUP_FILE -C $BACKUP_BASE_DIR/tmp >>/dev/null
 
-    for exclude in $DBEXCLUDE ; do
-        DBNAMES=$(echo $DBNAMES | sed "s/\b$exclude\b//g")
-    done
+    PG_DUMP_FILE=`find -P $BACKUP_BASE_DIR/tmp -name "dump.sql"`
+    PG_CONF_FILE=`find -P $BACKUP_BASE_DIR/tmp -name "postgresql.conf"`
+    PG_HBA_CONF=`find -P $BACKUP_BASE_DIR/tmp -name "pg_hba.conf"`
+    PG_AUTO_CONF=`find -P $BACKUP_BASE_DIR/tmp -name "postgresql.auto.conf"`
+    PG_IDENT_CONF=`find -P $BACKUP_BASE_DIR/tmp -name "pg_ident.conf"`
 
-    for DB in $DBNAMES ; do
-        DB_old=$DB"_old"
-        echo "==> alter database $DB rename to $DB_old..."
-        su postgres -c "psql -U postgres -Atc \"alter database $DB rename to $DB_old;\"" >>/dev/null
-    done
-
-    echo "==> restore. cmd:  psql -f $BACKUP_FILE ..."
-
-    su postgres -c "psql -f $BACKUP_FILE 2>&1" >>/dev/null
-
-    supervisorctl status postgres | grep 'RUNNING' >>/dev/null
-    if [ $? -ne 0 ]; then
-        echo "ERROR. restore failed. postgres is not running. rollback ..."
-        supervisorctl restart postgres
-
-        for DB in $DBNAMES ; do
-            DB_old=$DB"_old"
-            echo "==> alter database $DB rename to $DB_old ..."
-            su postgres -c "psql -U postgres -Atc \"alter database $DB_old rename to $DB;\"" >>/dev/null
-        done
+    if [ ! -f "$PG_DUMP_FILE" ] || [ ! -f "$PG_CONF_FILE" ] || [ ! -f "$PG_HBA_CONF" ]; then
+        skylar_log "ERROR" "cannot find files:$PG_DUMP_FILE or $PG_CONF_FILE or $PG_HBA_CONF."
+        rm -rf $BACKUP_BASE_DIR/tmp
         return 1
     fi
 
-    for DB in $DBNAMES ; do
-        DB_old=$DB"_old"
-        echo "==> drop database if exists $DB_old ..."
-        su postgres -c "psql -U postgres -Atc \"drop database if exists $DB_old;\"" >>/dev/null
-    done
+    return 0
+}
 
+restore_pg() {
+    skylar_log "INFO" "==> start to restore pg ..."
+
+    # step 0. check backup files valid
+    if ! check_backup_file; then
+        return 1
+    fi
+
+    # step 1. stop pg
+    skylar_log "INFO" "==> stop pg ..."
+    supervisorctl stop postgres >>/dev/null
+    kill -9 $(ps -ef | grep postgres | awk {'print $2'})
+
+    # step 2. backup old data to tmp
+    skylar_log "INFO" "==> backup $PG_DATA_DIR to $PG_DATA_OLD ..."
+    [ -d $PG_DATA_OLD ] && rm -rf $PG_DATA_OLD
+    ## cannot move directly. so we copy then remove.
+    cp -rf $PG_DATA_DIR $PG_DATA_OLD
+    rm -rf $PG_DATA_DIR
+
+    # step 3. create new db
+    skylar_log "INFO" "==> create new db ..."
+    mkdir -p "$PG_DATA_DIR"
+    chown -R postgres:postgres $PG_DATA_DIR
+    chmod -R 700 $PG_DATA_DIR
+
+    su postgres -c "$INITDB_BIN -D $PG_DATA_DIR"
+    sleep 5
+    su postgres -c "$PGCTL_BIN -D $PG_DATA_DIR -l logfile stop"
+    supervisorctl stop postgres
+    kill -9 $(ps -ef | grep postgres | awk {'print $2'})
+    ### restore config files
+    cp $PG_CONF_FILE $PG_DATA_DIR
+    cp $PG_HBA_CONF $PG_DATA_DIR
+    cp $PG_IDENT_CONF $PG_DATA_DIR
+    cp $PG_AUTO_CONF $PG_DATA_DIR
+
+    # step 4. import dump.sql
+    supervisorctl start postgres
+    su postgres -c "psql -f $PG_DUMP_FILE 2>&1" >>/dev/null
+    rm -rf $BACKUP_BASE_DIR/tmp
+
+    # step 5. succeed or rollback.
+    if ! supervisorctl status postgres; then
+        skylar_log "ERROR" "restore failed. rollback ..."
+        [ -d $PG_DATA_DIR ] && rm -rf $PG_DATA_DIR
+        mv $PG_DATA_OLD $PG_DATA_DIR
+
+        supervisorctl stop postgres
+        kill -9 $(ps -ef | grep postgres | awk {'print $2'})
+        supervisorctl start postgres
+        exit 1
+    fi
+
+    rm -rf $PG_DATA_OLD
     return 0
 }
 
 
 main() {
+    if ! check_args_valid; then
+        exit 1
+    fi
+
     restore_pg
 
     if [ $? -eq 0 ]; then
-        echo "Done."
+        skylar_log "INFO" "Done."
         exit 0
     else
-        echo "Failed."
+        skylar_log "ERROR" "Failed."
         exit 1
     fi
 }
 
 
-args=`getopt "i:d:hV" $*`
+args=`getopt "i:f:hV" $*`
 if [ $? -ne 0 ]
 then
     usage
@@ -196,7 +239,7 @@ for i in $*
 do
     case "$i" in
     -i) INDEX=$2; shift 2;;
-    -d) DIRRECTORY=$2; shift 2;;
+    -f) BACKUP_FILE=$2; shift 2;;
     -h) usage;;
     -V) echo "version $VERSION"; exit 0;;
     -\?) usage;;
diff --git a/redis/skylar_backup b/redis/skylar_backup
--- a/redis/skylar_backup
+++ b/redis/skylar_backup
@@ -6,11 +6,14 @@
 
 VERSION="1.0.0"
 BACKUP_BASE_DIR="/backup/container_redis"
-BACKUPDIR=""
+
 DIRRECTORY=""                       # the relative directory path of backup files. 
 RESERVE_SIZE=5                      # reserve space size GB
 
+BACKUP_FILE=""
 REDIS_AOF_FILE="/var/lib/redis/appendonly.aof"
+REDIS_RDB_FILE="/var/lib/redis/dump.rdb"
+REDIS_CONF_FILE="/var/lib/redis/redis.conf"
 
 REDIS_CLI=`which redis-cli`
 
@@ -18,11 +21,11 @@ usage() {
     echo "
 usage:
 
-docker exec -it redis bash backup [options]
+docker exec redis backup [options]
 
 the most commonly options are:
--d  directory       the relative directory path of backup files. 
-                    default is the timestamp. e.g: -d 20161201000000
+-f  file            backup data to the specify file. default is: /backup/container_main/<timestamp>.tar. 
+                    e.g: -f /backup/container_main/20161201000000.tar
 
 -r  reservespace    the reserve space size (unit GBytes). Backup will return error
                     if there is not enough reserve space. default is 5GB. e.g: -r 10
@@ -31,35 +34,60 @@ the most commonly options are:
 -h                  show this usage.
 
 example:
-docker exec -it redis bash backup
+docker exec redis backup
 "
     exit 0
+}
+
+## skylar_log <level> <content>
+skylar_log() {
+    echo "$2"
+    echo  "`date` $1 $2" >> /var/log/skylar_backup_restore.log
+}
+
+check_args_valid() {
+    if [ "$BACKUP_FILE" == "" ]; then
+        datetime=`date "+%Y%m%d%H%M%S"`
+        BACKUP_FILE="$BACKUP_BASE_DIR/$datetime"".tar"
+    fi
+
+    FILE=`basename $BACKUP_FILE`
+    echo "$FILE" | grep -q '^[a-zA-Z0-9\.]\+$' >>/dev/null
+    if [ $? -ne 0 ]; then
+        skylar_log "ERROR" "Invalid name of backupfile: $BACKUP_FILE"
+        exit 1
+    fi
+
+    echo "$BACKUP_FILE" | grep '.tar' >>/dev/null
+    if [ $? -ne 0 ]; then
+        skylar_log "ERROR" "Invalid name of backupfile: $BACKUP_FILE"
+        exit 1
+    fi
+
+    echo "$BACKUP_FILE" | grep '/backup/container_redis' >>/dev/null
+    if [ $? -ne 0 ]; then
+        skylar_log "ERROR" "Invalid name of backupfile: $BACKUP_FILE"
+        exit 1
+    fi
+
+    if [ -f $BACKUP_FILE ]; then
+        skylar_log "ERROR" "$BACKUP_FILE is exist."
+        exit 1
+    fi
 }
 
 ## we will create a directory specified by argument '-d'.
 ## if '-d' is empty, we will create a default directory named by timestamp. 
 create_backup_dir() {
-    echo "==> create backup directory ..."
-
-    if [ "$DIRRECTORY" == "" ]; then
-        DIRRECTORY=`date "+%Y%m%d%H%M%S"`
-    fi
-
-    BACKUPDIR="$BACKUP_BASE_DIR/$DIRRECTORY"
-
-    if [ -d $BACKUPDIR ]; then
-        echo "ERROR. $BACKUPDIR is already exsit."
-        exit 1
-    fi
-
-    mkdir -p $BACKUPDIR
+    skylar_log "INFO" "==> create backup directory ..."
+    [ ! -d $BACKUP_BASE_DIR ] && mkdir -p $BACKUP_BASE_DIR 
 }
 
 
 ## check_space $need_size. unit Bytes. 
 ## return 0 if free space is enough, else return 1.
 check_space() {
-    echo "==> check space ..."
+    skylar_log "INFO" "==> check space ..."
 
     need_size=0
     if [ "$1" != "" ]; then
@@ -68,6 +96,11 @@ check_space() {
 
     cd /
     total_free_size=`df | grep '/dev/mapper/docker' | awk '{print $4}'`
+    df | grep '/etc/hosts' >>/dev/null
+    if [ $? -eq 0 ]; then
+        total_free_size=`df | grep '/dev/mapper/docker' | awk '{print $4}'`
+    fi
+
     let total_free_size=$total_free_size*1024
     let free_size=$total_free_size-$need_size
     let reserve_bytes=$RESERVE_SIZE*1024*1024
@@ -77,11 +110,11 @@ check_space() {
     let free_size_MB=$free_size/1024/1024
     let reserve_size_MB=$reserve_bytes/1024/1024
 
-    echo "==> compute space size ..."
-    echo "total_free_size=$total_free_size_MB MBytes."
-    echo "need_size=$need_size_MB MBytes."
-    echo "free_size=$free_size_MB MBytes."
-    echo "reserve_size=$reserve_size_MB MBytes."
+    skylar_log "INFO" "==> compute space size ..."
+    skylar_log "INFO" "total_free_size=$total_free_size_MB MBytes."
+    skylar_log "INFO" "need_size=$need_size_MB MBytes."
+    skylar_log "INFO" "free_size=$free_size_MB MBytes."
+    skylar_log "INFO" "reserve_size=$reserve_size_MB MBytes."
 
     if [ $free_size -lt $reserve_bytes ]; then
         return 1
@@ -91,45 +124,54 @@ check_space() {
 }
 
 backup_aof() {
-    echo "==> start to backup aof ..."
+    skylar_log "INFO" "==> start to backup aof ..."
 
     if [ ! -e $REDIS_AOF_FILE ]; then
-        echo "WARN. $REDIS_AOF_FILE is not exsit yet. I will create it by cmd: $REDIS_CLI bgrewriteaof."
+        skylar_log "WARN" "WARN. create aof by cmd: $REDIS_CLI bgrewriteaof."
         $REDIS_CLI bgrewriteaof
     fi
 
     if [ ! -e $REDIS_AOF_FILE ]; then
-        echo "ERROR. cannot find $REDIS_AOF_FILE."
+        skylar_log "ERROR" "ERROR. cannot find $REDIS_AOF_FILE."
         return 1
     fi
 
     aof_size=`ls -l $REDIS_AOF_FILE | awk '{print $5}'`
     check_space $aof_size
     if [ $? -ne 0 ]; then
-        echo "ERROR. There is not enough reserve space to backup $REDIS_AOF_FILE. Reserve size is $RESERVE_SIZE GB."
+        skylar_log "ERROR" "ERROR. There is not enough reserve space to backup $REDIS_AOF_FILE. Reserve size is $RESERVE_SIZE GB."
         return 1
     fi
 
     create_backup_dir
 
-    cp $REDIS_AOF_FILE $BACKUPDIR
-
-    return 0
+    cd $BACKUP_BASE_DIR
+    rm -f appendonly.aof dump.rdb redis.conf
+    cp -f $REDIS_AOF_FILE appendonly.aof
+    cp -f $REDIS_RDB_FILE dump.rdb
+    cp -f $REDIS_CONF_FILE redis.conf
+    tar cvf $BACKUP_FILE appendonly.aof dump.rdb redis.conf
+    rm -f appendonly.aof dump.rdb redis.conf
+    return $?
 }
 
 main() {
+    if ! check_args_valid; then
+        exit 1
+    fi
+
     backup_aof
 
     if [ $? -eq 0 ]; then
-        echo "Done."
+        skylar_log "INFO" "Done."
         exit 0
     else
-        echo "Failed."
+        skylar_log "ERROR" "Failed."
         exit 1
     fi
 }
 
-args=`getopt "d:r:hV" $*`
+args=`getopt "f:r:hV" $*`
 if [ $? -ne 0 ]
 then
     usage
@@ -139,7 +181,7 @@ set -- $args
 for i in $*
 do
     case "$i" in
-    -d) DIRRECTORY=$2; shift 2;;
+    -f) BACKUP_FILE=$2; shift 2;;
     -r) RESERVE_SIZE=$2; shift 2;;
     -h) usage;;
     -V) echo "version $VERSION"; exit 0;;
diff --git a/redis/skylar_restore b/redis/skylar_restore
--- a/redis/skylar_restore
+++ b/redis/skylar_restore
@@ -14,6 +14,7 @@ REDIS_AOF_FILE="/var/lib/redis/appendonly.aof"
 REDIS_AOF_FILE_OLD="/var/lib/redis/appendonly.aof.old"
 
 BACKUP_FILE=""
+AOF_FILE=""
 
 REDIS_CLI=`which redis-cli`
 
@@ -21,7 +22,7 @@ usage() {
     echo "
 usage:
 
-docker exec -it redis bash restore [options]
+docker exec redis restore [options]
 
 the most commonly options are:
 -i  index       restore with a directory by index. 
@@ -33,11 +34,17 @@ the most commonly options are:
 -h              show this usage.     
 
 example:
-docker exec -it redis bash restore
+docker exec redis restore
 "
     exit 0
 }
 
+
+## skylar_log <level> <content>
+skylar_log() {
+    echo "$2"
+    echo  "`date` $1 $2" >> /var/log/skylar_backup_restore.log
+}
 
 ## check_space $need_size. return 0 or 1
 check_space() {
@@ -45,7 +52,7 @@ check_space() {
     if [ "$1" != "" ] && [ "$1" -gt 0 ]; then
         need_size=$1
     else
-        echo "ERROR. get an invalid aof file size."
+        skylar_log "ERROR" "ERROR. get an invalid aof file size."
         return 1
     fi
 
@@ -60,11 +67,11 @@ check_space() {
     let free_size_MB=$free_size/1024/1024
     let reserve_size_MB=$reserve_bytes/1024/1024
 
-    echo "==> compute space size ..."
-    echo "total_free_size=$total_free_size_MB MBytes."
-    echo "need_size=$need_size_MB MBytes."
-    echo "free_size=$free_size_MB MBytes."
-    echo "reserve_size=$reserve_size_MB MBytes."
+    skylar_log "INFO" "==> compute space size ..."
+    skylar_log "INFO" "total_free_size=$total_free_size_MB MBytes."
+    skylar_log "INFO" "need_size=$need_size_MB MBytes."
+    skylar_log "INFO" "free_size=$free_size_MB MBytes."
+    skylar_log "INFO" "reserve_size=$reserve_size_MB MBytes."
 
     if [ $free_size -lt $reserve_bytes ]; then
         return 1
@@ -74,84 +81,111 @@ check_space() {
 }
 
 
-restore_aof() {
-    echo "==> start to restore redis ..."
-
+check_backup_file() {
     ## try to use index at first.
     if [ "$INDEX" != "" ] && [ "$INDEX" -gt 0 ]; then
-        DIRRECTORY=`ls -lt | sed '1d' | sed -n "$INDEXp" | awk '{print $9}'`
-        if [ "$DIRRECTORY" == "" ]; then
-            echo "ERROR. get an invalid index:$INDEX."
+        cd $BACKUP_BASE_DIR
+        FILE=`ls -lt | sed '1d' | sed -n "$INDEX p" | awk '{print $9}'`
+        if [ ! -f "$FILE" ]; then
+            skylar_log "ERROR" "ERROR. get an invalid index:$INDEX."
             return 1
         fi
+        BACKUP_FILE=$BACKUP_BASE_DIR/$FILE
     fi
 
-    if [ "$DIRRECTORY" == "" ] && [ "$INDEX" == "" ]; then
+    if [ "$BACKUP_FILE" == "" ] && [ "$INDEX" == "" ]; then
         if [ ! -d $BACKUP_BASE_DIR ]; then
-            echo "ERROR. cannot find directory $BACKUP_BASE_DIR."
+            skylar_log "ERROR" "ERROR. cannot find directory $BACKUP_BASE_DIR."
             return 1
         fi
         cd $BACKUP_BASE_DIR
-        DIRRECTORY=`ls -lt | sed '1d' | head -1 | awk '{print $9}'`
-        if [ "$DIRRECTORY" == "" ]; then
-            echo "ERROR. Backup directory is empty."
+
+        FILE=`ls -lt | sed '1d' | head -1 | awk '{print $9}'`
+        if [ ! -f "$FILE" ]; then
+            skylar_log "ERROR" "ERROR. Backup directory is empty."
             return 1
         fi
+        BACKUP_FILE=$BACKUP_BASE_DIR/$FILE
     fi
-
-    BACKUP_FILE="$BACKUP_BASE_DIR/$DIRRECTORY/appendonly.aof"
-    if [ ! -e $BACKUP_FILE ]; then
-        echo "ERROR. cannot find backup file: $BACKUP_FILE"
+    if [ ! -f "$BACKUP_FILE" ]; then
+        skylar_log "ERROR" "cannot find file:$BACKUP_FILE"
         return 1
     fi
 
-    echo "==> $BACKUP_FILE will be used to restore ..."
-
-    aof_size=`ls -l $BACKUP_FILE | awk '{print $5}'`
-    check_space $aof_size
+    size=`ls -l $BACKUP_FILE | awk '{print $5}'`
+    check_space $size
     if [ $? -ne 0 ]; then
-        echo "ERROR. There is not enough reserve space to restore. reserve size is $RESERVE_SIZE GB."
+        skylar_log "ERROR" "ERROR. There is not enough reserve space to restore. reserve size is $RESERVE_SIZE GB."
         return 1
     fi
 
-    cp $REDIS_AOF_FILE $REDIS_AOF_FILE_OLD
+    [ -d $BACKUP_BASE_DIR/tmp ] && rm -rf $BACKUP_BASE_DIR/tmp
+    mkdir -p $BACKUP_BASE_DIR/tmp
+    cd $BACKUP_BASE_DIR
+    tar xvf $BACKUP_FILE -C $BACKUP_BASE_DIR/tmp >>/dev/null
 
-    echo "==> supervisorctl stop redis ..."
-    supervisorctl stop redis
-    kill -9 $(ps -ef | grep redis-server | grep 6379 | awk '{print $2}')
+    AOF_FILE=`find -P $BACKUP_BASE_DIR/tmp -name "appendonly.aof"`
 
-    echo "==> copy $BACKUP_FILE to $REDIS_AOF_FILE ..."
-    cp $BACKUP_FILE $REDIS_AOF_FILE
-
-    echo "==> supervisorctl start redis ..."
-    supervisorctl start redis
-
-    if [ $? -ne 0 ]; then
-        echo "ERROR. supervisorctl start redis failed. rollback and restart redis ..."
-        mv $REDIS_AOF_FILE_OLD $REDIS_AOF_FILE
-        supervisorctl restart redis
+    if [ ! -f "$AOF_FILE" ]; then
+        skylar_log "ERROR" "cannot find files:$AOF_FILE."
+        rm -rf $BACKUP_BASE_DIR/tmp
         return 1
     fi
 
-    rm -f $REDIS_AOF_FILE_OLD
     return 0
 }
 
+restore_aof() {
+    skylar_log "INFO" "==> start to restore redis ..."
+
+    # step 0. check backup files.
+    if ! check_backup_file; then
+        exit 1
+    fi
+
+    # step 1. stop redis
+    skylar_log "INFO" "==> supervisorctl stop redis ..."
+    supervisorctl stop redis
+    ps -ef | grep redis-server >>/dev/null
+    if [ $? -eq 0 ]; then
+        kill -9 $(ps -ef | grep redis-server | grep 6379 | awk '{print $2}') >>/dev/null
+    fi
+
+    # step 2. restore aof
+    skylar_log "INFO" "==> $AOF_FILE will be used to restore ..."
+
+    cp $REDIS_AOF_FILE $REDIS_AOF_FILE_OLD
+    cp $AOF_FILE $REDIS_AOF_FILE
+    
+    # step 3. succeed or rollback.
+    skylar_log "INFO" "==> supervisorctl start redis ..."
+    if ! supervisorctl start redis; then
+        skylar_log "ERROR" "ERROR. supervisorctl start redis failed. rollback and restart redis ..."
+        mv $REDIS_AOF_FILE_OLD $REDIS_AOF_FILE
+        supervisorctl restart redis
+        rm -rf $BACKUP_BASE_DIR/tmp
+        return 1
+    fi
+
+    rm -rf $BACKUP_BASE_DIR/tmp
+    rm -f $REDIS_AOF_FILE_OLD
+    return 0
+}
 
 main() {
     restore_aof
 
     if [ $? -eq 0 ]; then
-        echo "Done."
+        skylar_log "INFO" "Done."
         exit 0
     else
-        echo "Failed."
+        skylar_log "ERROR" "Failed."
         exit 1
     fi
 }
 
 
-args=`getopt "i:d:hV" $*`
+args=`getopt "i:f:hV" $*`
 if [ $? -ne 0 ]
 then
     usage
@@ -162,7 +196,7 @@ for i in $*
 do
     case "$i" in
     -i) INDEX=$2; shift 2;;
-    -d) DIRRECTORY=$2; shift 2;;
+    -f) BACKUP_FILE=$2; shift 2;;
     -h) usage;;
     -V) echo "version $VERSION"; exit 0;;
     -\?) usage;;
